import { PeerStudent, CampusStudySquad, PeerDirectMessage } from './types';

export const INITIAL_PEER_STUDENTS: PeerStudent[] = [
  {
    id: 'peer_1',
    name: 'Zainab Al-Hassan',
    institutionCode: 'ABU',
    institutionName: 'Ahmadu Bello University',
    department: 'Civil Engineering',
    level: '300L',
    isOnline: true,
    verified: true,
    stringAccountId: 'str_biz_zainab_tech',
    bio: 'Structural analysis & CAD models. Building sustainable bridges.',
  },
  {
    id: 'peer_2',
    name: 'Chukwuemeka Okoye',
    institutionCode: 'UNN',
    institutionName: 'University of Nigeria, Nsukka',
    department: 'Pharmacy',
    level: '400L',
    isOnline: true,
    verified: true,
    stringAccountId: 'str_cus_emeka_pharma',
    bio: 'Pharmacokinetics & medicinal chemistry. Exam drill partner wanted.',
  },
  {
    id: 'peer_3',
    name: 'Toluwanimi Adeleke',
    institutionCode: 'OOU',
    institutionName: 'Olabisi Onabanjo University',
    department: 'Economics',
    level: '200L',
    isOnline: false,
    verified: true,
    stringAccountId: 'str_cus_tolu_eco',
    bio: 'Macroeconomics, Game Theory & Econometrics notes exchange.',
  },
  {
    id: 'peer_4',
    name: 'Ayomide Balogun',
    institutionCode: 'UNILAG',
    institutionName: 'University of Lagos',
    department: 'Computer Science',
    level: '300L',
    isOnline: true,
    verified: true,
    stringAccountId: 'str_biz_ayomide_dev',
    bio: 'Algorithms, Data Structures & System Design enthusiast.',
  },
  {
    id: 'peer_5',
    name: 'Blessing Danjuma',
    institutionCode: 'UI',
    institutionName: 'University of Ibadan',
    department: 'Biochemistry',
    level: '400L',
    isOnline: false,
    verified: true,
    bio: 'Enzyme kinetics & molecular biology research assistant.',
  },
  {
    id: 'peer_6',
    name: 'Kafayat Salami',
    institutionCode: 'LASU',
    institutionName: 'Lagos State University',
    department: 'Law',
    level: '300L',
    isOnline: true,
    verified: true,
    stringAccountId: 'str_biz_kafayat_law',
    bio: 'Jurisprudence & Constitutional Law mock trial researcher.',
  },
  {
    id: 'peer_7',
    name: 'David Oladipo',
    institutionCode: 'FUTA',
    institutionName: 'Federal University of Technology, Akure',
    department: 'Electrical & Electronics Engineering',
    level: '500L',
    isOnline: true,
    verified: true,
    bio: 'Embedded systems, power distribution & robotics final year project.',
  },
  {
    id: 'peer_8',
    name: 'Ngozi Ezechukwu',
    institutionCode: 'CU',
    institutionName: 'Covenant University',
    department: 'Accounting',
    level: '200L',
    isOnline: false,
    verified: true,
    stringAccountId: 'str_cus_ngozi_fin',
    bio: 'Financial reporting, auditing standards & ICAN stage one.',
  },
];

export const INITIAL_STUDY_SQUADS: CampusStudySquad[] = [
  {
    id: 'squad_1',
    name: 'National General Studies (GNS) CBT Sprint',
    topic: 'GNS 101/201 General Studies CBT Revision & Timed Mock Questions',
    courseCode: 'GNS 101',
    institutionCode: 'ALL',
    memberCount: 342,
    lastActive: '5m ago',
    isPublic: true,
    tags: ['CBT', 'All Unis', 'Revision', 'GNS'],
  },
  {
    id: 'squad_2',
    name: 'Macroeconomics 200L Peer Roundtable',
    topic: 'IS-LM Curve shifts, monetary aggregates & central bank policy',
    courseCode: 'ECO 201',
    institutionCode: 'OOU',
    memberCount: 58,
    lastActive: '12m ago',
    isPublic: true,
    tags: ['Economics', 'Past Questions', 'Lectures'],
  },
  {
    id: 'squad_3',
    name: 'UNILAG CS & Tech Builders',
    topic: 'Data Structures, Graph Traversals, LeetCode & Semester Practicals',
    courseCode: 'CSC 301',
    institutionCode: 'UNILAG',
    memberCount: 124,
    lastActive: 'Just now',
    isPublic: true,
    tags: ['CS', 'Coding', 'Practicals'],
  },
  {
    id: 'squad_4',
    name: 'Clinical Pharmacy Drug Interactions Guild',
    topic: 'Cardiovascular agents, dosage calculation formulas & ward rounds',
    courseCode: 'PHA 402',
    institutionCode: 'UNN',
    memberCount: 89,
    lastActive: '2h ago',
    isPublic: true,
    tags: ['Pharmacy', 'Clinical', 'Exam Drill'],
  },
];

export const INITIAL_DIRECT_MESSAGES: Record<string, PeerDirectMessage[]> = {
  peer_1: [
    {
      id: 'dm_1',
      senderId: 'peer_1',
      receiverId: 'usr_me',
      content: 'Hey scholar! Did you review the structural analysis formulas from chapter 3?',
      timestamp: '10:24 AM',
      type: 'text',
      isRead: true,
    },
    {
      id: 'dm_2',
      senderId: 'usr_me',
      receiverId: 'peer_1',
      content: 'Yes! Just ran a drill on Cohart AI. The bending moment diagram model was super clear.',
      timestamp: '10:27 AM',
      type: 'text',
      isRead: true,
    },
    {
      id: 'dm_3',
      senderId: 'peer_1',
      receiverId: 'usr_me',
      content: 'Awesome. If you need any drafting materials, check my linked String merchant store too!',
      timestamp: '10:30 AM',
      type: 'text',
      isRead: true,
    },
  ],
  peer_4: [
    {
      id: 'dm_4',
      senderId: 'peer_4',
      receiverId: 'usr_me',
      content: 'Yo! We are solving dynamic programming practice questions in our squad right now.',
      timestamp: '1:15 PM',
      type: 'text',
      isRead: true,
    },
  ],
};
